baseURL = 'https://claydav.is/'
languageCode = 'en-us'
title = 'Clay Davis'

[imaging]
  quality = 75

[params]
  author = "Clay Davis"
  description = "Mellon Postdoctoral Fellow in the Department of Science & Technology Studies and the Society for the Humanities at Cornell University"

[params.contact]
  email = "cdavis@u.northwestern.edu"
  scholar = "https://scholar.google.com/citations?hl=en&user=ZuazMDwAAAAJ"
  bluesky = "https://bsky.app/profile/claydav.is"
  
[params.colors]
  primary = "#2D6F59"
  primary_medium = "#6c9a8a"
  primary_light = "#abc5bc"
  surface = "#ffffff"
  gray = "#f3f3f3"
  text = "#000000"
  text_secondary = "#333333"

[params.widgets]
  bluesky_handle = "claydav.is"
  goodreads_user_id = "31220050"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"


[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/"
    weight = 10

  [[menu.main]]
    name = "Research"
    pageRef = "/research"
    weight = 20

  [[menu.main]]
    name = "CV"
    pageRef = "/cv"
    weight = 30

  [[menu.main]]
    name = "Teaching"
    pageRef = "/teaching"
    weight = 40

  [[menu.main]]
    name = "Meet with me"
    pageRef = "/meetwithme/officehours"
    weight = 50
